#Configurações do Scraper
LATTES_WORKER_COUNT = 2 
JSON_FILE_PATH = "data/professors.json" 

# --- Departamentos ---
ALL_DEPARTMENTS = [
            "CAMPUS UNB GAMA: FACULDADE DE CIÊNCIAS E TECNOLOGIAS EM ENGENHARIA - BRASÍLIA",
            "DEPTO CIÊNCIAS DA COMPUTAÇÃO - BRASÍLIA",
            "DEPARTAMENTO DE MATEMÁTICA - BRASÍLIA",
            "FACULDADE DE CIÊNCIA DA INFORMAÇÃO - BRASÍLIA",
            "FACULDADE DE TECNOLOGIA - BRASÍLIA",
            "DEPTO ESTATÍSTICA - BRASÍLIA",
            "FACULDADE DE ARQUITETURA E URBANISMO - BRASÍLIA",
            "INSTITUTO DE FÍSICA - BRASÍLIA",
    # "INSTITUTO DE GEOCIÊNCIAS - BRASÍLIA", 
    "INSTITUTO DE QUÍMICA - BRASÍLIA",
]