#Configurações do Scraper
LATTES_WORKER_COUNT = 2 
JSON_FILE_PATH = "data/professors.json" 

# --- Departamentos ---
ALL_DEPARTMENTS = [
            "CAMPUS UNB GAMA: FACULDADE DE CIÊNCIAS E TECNOLOGIAS EM ENGENHARIA - BRASÍLIA",
            "DEPTO CIÊNCIAS DA COMPUTAÇÃO - BRASÍLIA",
            "DEPARTAMENTO DE MATEMÁTICA - BRASÍLIA",
            "FACULDADE DE CIÊNCIA DA INFORMAÇÃO - BRASÍLIA",
            "FACULDADE DE TECNOLOGIA - BRASÍLIA",
            "DEPTO ESTATÍSTICA - BRASÍLIA",
            "FACULDADE DE ARQUITETURA E URBANISMO - BRASÍLIA",
            "INSTITUTO DE FÍSICA - BRASÍLIA",
            "DEPTO ENGENHARIA CIVIL E AMBIENTAL - BRASÍLIA",
            "INSTITUTO DE QUÍMICA - BRASÍLIA",
            "DEPARTAMENTO DE ENGENHARIA MECANICA - BRASÍLIA",
            "DEPTO ENGENHARIA DE PRODUCAO - BRASÍLIA",
            "DEPTO ENGENHARIA ELETRICA - BRASÍLIA",
            "DEPTO ENGENHARIA FLORESTAL - BRASÍLIA",
            # "INSTITUTO DE GEOCIÊNCIAS - BRASÍLIA",
]