# .github/workflows/deploy.yml

name: Publicar no GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      
      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Deploy do site
        run: mkdocs gh-deploy --force --clean