name: Scraping POC (SIGAA)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}
  schedule:
    - cron: "0 12 * * *" # 09h de Brasília

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4
          python -m playwright install --with-deps

      - name: Rodar raspagem SIGAA
        run: python scraper_sigaa.py

      - name: Upload do JSON gerado
        uses: actions/upload-artifact@v4
        with:
          name: professores-json
          path: professores.json
