name: Test Lattes Scraper on Actions

on:
  workflow_dispatch:

jobs:
  test-scraper-job:
    runs-on: ubuntu-latest 
    
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: 1. Fazer checkout do seu código
        uses: actions/checkout@v4

      - name: 2. Configurar o Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 3. Instalar dependências do Python
        run: |
          python -m pip install --upgrade pip
          # Instala as dependências do seu backend/requirements.txt
          pip install -r requirements.txt 

      - name: 4. Instalar o navegador Chromium do Playwright
        run: |
          playwright install chromium # Só precisamos do Chromium

      - name: 5. Instalar o Xvfb (a "Tela Virtual")
        run: |
          # Precisamos sair do diretório de trabalho padrão para instalar pacotes do sistema
          sudo apt-get update
          sudo apt-get install -y xvfb
        working-directory: . 

      - name: 6. Rodar o Scraper (headless=False) dentro do Xvfb
        run: |
          # Este comando inicia a "tela virtual" e
          # roda seu script python (que já está dentro da pasta 'backend')
          # É AQUI QUE O ERRO DE CAPTCHA VAI ACONTECER.
          xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" \
          python scraper_runner.py